version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "canary-deploy-sam-repeat"
s3_bucket = "codedeploy-automate-bucket-webinar-live"
s3_prefix = "canary-deploy-sam-repeat"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
