version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "canary-deploy-sam-v2"
s3_bucket = "hooksbucket"
s3_prefix = "canary-deploy-sam-v2"
region = "ap-south-1"
profile = "personal"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
