# Phase-1:
service: codedeploy-rollback
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-south-1
package:
  individually: true
  exclude:
    - './**'

  
plugins:
  - serverless-plugin-aws-alerts
  - serverless-plugin-canary-deployments



#Phase-2:
custom:
  alerts:
    dashboards: true
    definitions: 
      FunctionErrors:
        namespace: 'AWS/Lambda'
        metric: Errors
        threshold: 1
        statistic: Minimum
        period: 60
        evaluationPeriods: 1
        comparisonOperator: GreaterThanOrEqualToThreshold
 

#Phase-3:
functions:
  Order:
    handler: orders.getOrders
    package:
      include:
        - orders.js
    events:
      - http: GET /order
    alarms:
      - FunctionErrors
    deploymentSettings:
      type: Linear10PercentEvery1Minute
      alias: Live
      alarms: 
        - OrderFunctionErrorsAlarm

  Product:
    handler: products.getProducts
    package:
      include:
        - products.js
    events:
      - http: get /product
    alarms:
      - FunctionErrors
    deploymentSettings:
      type: Linear10PercentEvery1Minute
      alias: Live
      alarms: 
        - ProductFunctionErrorsAlarm



















