AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31
  
Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "OrderLambdaFunction"
      Handler: order.handler
      Runtime: nodejs16.x
      CodeUri: functions
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Linear10PercentEvery1Minute 
        Alarms:
          - !Ref CloudWatchAlarm   
        Hooks:
          PreTraffic: !Ref HooksLambda
      Events:
        OrderRestAPI:
          Type: Api
          Properties:
            Method: GET
            Path: /

  CloudWatchAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      ActionsEnabled: true
      AlarmName: lambda-cloudwatch-alarm
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Minimum
      Threshold: 1
      DatapointsToAlarm: 1
      Period: 30

  
  HooksLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CodeDeployHook_PreTrafficLambda
      Handler: hooks.pre
      Runtime: nodejs16.x
      CodeUri: hooks
      Environment:
        Variables:
          LambdaCurrentVersion: !Ref MyLambdaFunction.Version
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: "*"
              Resource: "*"


  
  # HooksLambdaPost:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Handler: hooks.post
  #     Runtime: nodejs12.x
  #     CodeUri: functions
  #     Policies:
  #       - AWSLambdaExecute
  #       - Version: "2012-10-17"
  #         Statement:
  #           - Effect: Allow
  #             Action: "*"
  #             Resource: "*"
